version: "3"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - 'INFLUXDB_DATA_ENGINE=tsm1'
      - 'INFLUXDB_REPORTING_DISABLED=false'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /tmp/data/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - 'GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource'
    links:
      - influxdb